### ISSUE TITLE
Non parametric bootstrap

### ISSUE THREAD

**Issue by DaMingScripts** [fanhuan/AAF#3]
Hello, I ran AAF to make a tree very easily, but the bootstrap step is failing in reading the input files.
My command :
python nonparametric_bootstrap.py -k 21 -t 10 -d data --S1 2 --S2 2
(my data are fastq.gz files in the folder data)
And I got that error :
sp1
sp2
...
last_sp
1 out of 3 times of bootstrap over reads.
Traceback (most recent call last):
  File "nonparametric_bootstrap.py", line 316, in <module>
    for seq_record in SeqIO.parse(handle, seqFormat):
  File "/home/un/miniconda2/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 655, in parse
    for r in i:
  File "/home/un/miniconda2/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 1240, in FastqIlluminaIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/home/un/miniconda2/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 904, in FastqGeneralIterator
    "Records in Fastq files should start with '@' character")
ValueError: Records in Fastq files should start with '@' character

I suspect it could be due to the .gz compression of my data, but it was fine for the distance and tree building step... 
If I remove the first bootstrap step (--S1 0) and/or the second step (--S2 0), I get a broken pipe error :
...
gzip: stdout: Broken pipe

gzip: stdout: Broken pipe
Segmentation fault (core dumped)
Segmentation fault (core dumped)

gzip: stdout: Broken pipe

gzip: stdout: Broken pipe
Segmentation fault (core dumped)

I think it's not a big issue, but it prevent the bootstrap to be done... 
Thanks in advance, Damien

**Comment by devinbendixsen** [comment]
I am also having the same issue. Did anybody figure out how to fix this?
